export const products = [
  {
    id: "0",
    brand: "Rainy Days",
    name: "Dural pro",
    model: "unisex",
    price: 79,
    image: "../images/men-image.jpg",
    color: ["green", "white", "black"],
    size: ["S (small)", "M (medium)", "L (large)"],
    type: ["hiking, sport"],
    details: "Lorem ipsum dolor sit amet, per nulla harum te. Ne nec clita pertinacia mnesarchum. Duo nostro saperet cu, sed elitr cotidieque cu, alii pericula sit ex. Nec an aperiri ornatus. Hinc equidem necessitatibus ex eos, ex eos tation tamquam feugiat. Vim id solum quando erroribus, ad qui laudem nullam cetero, mel sanctus consequat comprehensam et. Ius suas quando perpetua ut, per in habeo volutpat intellegam. Ea quas virtute vis, te ius audire bonorum deleniti. Pro ne omnis delenit assueverit, ad natum reprehendunt mea, his at iuvaret euismod nostrum. Ad nemore mediocrem maiestatis duo, ius corpora consectetuer id, vim ei partem invidunt. Usu ad partem graeco adipiscing, pri rebum nostrud legimus te. Ius putent scripta maluisset in, graeco impetus rationibus quo ne. Eu per purto commune erroribus, et has suas tempor dignissim. Fabulas delenit imperdiet sea ex, at per labore animal. At duo delenit accommodare, eum ut assum dicit partiendo, has cu timeam constituam. Eam semper possim impedit cu. His aliquam vivendo voluptatum te, per falli dicam in. Has viditullum ea. Vis ei alii causae fierent, et est affert timeam. Sonet aperiam reprimique mei cu.",
  },
  {
    id: "1",
    brand: "Rainy Days",
    name: "Sport plus",
    model: "unisex",
    price: 79,
    image: "../images/product-golden1.jpg",
    color: ["brown", "white", "black"],
    size: ["S (small)", "M (medium)", "L (large)"],
    type: ["hiking, sport"],
    details: "Eos autem insolens splendide ne, tation libris mea id. Errem detraxit et est, sit omnis vidisse scaevola ne, integre graecis molestiae et nam. Cu modo enim minimum eos. An cum ridens delenit scribentur, ludus discere nominavi mea ea, id mea salutatus consectetuer. Ei persius tincidunt sea, homero graeco propriae mel et, ei erant corpora his. Iuvaret volutpat ut sea. Everti maluisset ne sit, wisi illum dolorem an qui.",
  },
  {
    id: "2",
    brand: "Rainy Days",
    name: "monday mood",
    model: "men",
    price: 59,
    image: "../images/product-silver.jpg",
    color: ["orange", "white", "black"],
    size: ["M (medium)", "L (large)", "XL (extra large)"],
    type: ["casual"],
    details: "Lorem ipsum dolor sit amet, per nulla harum te. Ne nec clita pertinacia mnesarchum. Duo nostro saperet cu, sed elitr cotidieque cu, alii pericula sit ex. Nec an aperiri ornatus. Hinc equidem necessitatibus ex eos, ex eos tation tamquam feugiat. Vim id solum quando erroribus, ad qui laudem nullam cetero, mel sanctus consequat comprehensam et. Ius suas quando perpetua ut, per in habeo volutpat intellegam. Pro ne omnis delenit assueverit, ad natum reprehendunt mea, his at iuvaret euismod nostrum. Ad nemore mediocrem maiestatis duo, ius corpora consectetuer id, vim ei partem invidunt. Usu ad partem graeco adipiscing, pri rebum nostrud legimus te. Fabulas delenit imperdiet sea ex, at per labore animal. At duo delenit accommodare, eum ut assum dicit partiendo, has cu timeam constituam. Eam semper possim impedit cu. His aliquam vivendo voluptatum te, per falli dicam in. Has viditullum ea. Vis ei alii causae fierent, et est affert timeam. Sonet aperiam reprimique mei cu.",
  },
  {
    id: "3",
    brand: "Rainy days",
    name: "happy friday",
    model: "women",
    price: 59,
    image: "../images/new-arrivals.jpg",
    color: ["yellow", "white", "black"],
    size: ["XS (extra small)", "S (small)", "M (medium)"],
    type: ["casual"],
    details: "Lorem ipsum dolor sit amet, per nulla harum te. Ne nec clita pertinacia mnesarchum. Duo nostro saperet cu, sed elitr cotidieque cu, alii pericula sit ex. Nec an aperiri ornatus. Hinc equidem necessitatibus ex eos, ex eos tation tamquam feugiat. Vim id solum quando erroribus, ad qui laudem nullam cetero, mel sanctus consequat comprehensam et. Ius suas quando perpetua ut, per in habeo volutpat intellegam. Pro ne omnis delenit assueverit, ad natum reprehendunt mea, his at iuvaret euismod nostrum.",
  },
];
