export const products = [
  {
    id: "0",
    brand: "Rainy Days",
    name: "Dural pro",
    model: "unisex",
    price: 79,
    image: "../images/men-image.jpg",
    color: ["red", "blue", "white", "black"],
    size: ["small", "medium", "large"],
    type: ["hiking, sport"],
  },
  {
    id: "1",
    brand: "Rainy Days",
    name: "Sport plus",
    model: "unisex",
    price: 79,
    image: "../images/product-golden1.jpg",
    color: ["green", "blue", "white", "black"],
    size: ["small", "medium", "large"],
    type: ["hiking, sport"],
  },
  {
    id: "2",
    brand: "Rainy Days",
    name: "monday mood",
    model: "men",
    price: 59,
    image: "../images/product-silver.jpg",
    color: ["yellow", "white", "black"],
    size: ["small", "medium", "large"],
    type: ["casual"],
  },
  {
    id: "3",
    brand: "Rainy days",
    name: "happy friday",
    model: "women",
    price: 59,
    image: "../images/new-arrivals.jpg",
    color: ["yellow", "white", "black"],
    size: ["small", "medium", "large"],
    type: ["casual"],
  },
];
